-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg9Yi50fhknuWuSbNw
Bn/Fq3qScq6hPtmvYr3QiW1lQf+gCgYIKoZIzj0DAQehRANCAASrXslC6pbRfv7k
qnT25WFmqkw4PMGA8UBw4u/AhYW4KmlKwhU/v0TqiYi1cu7ETkgscMCoSbwtnYu5
moif8fYs
-----END PRIVATE KEY-----