
-- steps for add vehicle
-- 1. vin code, 2. marka, 3. model, 4. year, 5. generations, 6. body types, 7. engine, 8. driveride, 
-- 9. transmission, 10. modification, 11. color, 12. images

-- drop table if exists complectations_exel;
-- drop table if exists configurations_exel;
-- drop table if exists generations_exel;
-- drop table if exists models_exel;
-- drop table if exists marks_exel;

-- create table marks_exel (
--     "id" serial primary key,
--     "inner_id" character varying(50) not null,
--     "name" character varying(50) not null,
--     "cyrillic_name" character varying(50) not null,
--     "numeric_id" int not null,
--     "logo" text,
--     "big_logo" text,
--     "year_from" int not null,
--     "year_to" int not null,
--     "updated_at" timestamp not null default now(),
--     "created_at" timestamp not null default now(),
--     unique(inner_id)
-- );

-- create table models_exel (
--     "id" serial primary key,
--     "autoru_mark_id" int not null,
--     "autoru_mark_inner_id" character varying(50) not null,
--     "inner_id" character varying(50) not null,
--     "name" character varying(50) not null,
--     "cyrillic_name" character varying(50) not null,
--     "year_from" int not null,
--     "year_to" int not null,
--     "updated_at" timestamp not null default now(),
--     "created_at" timestamp not null default now(),
--     constraint models_exel_autoru_mark_id_fk
--         foreign key("autoru_mark_id")
--             references marks_exel("id")
--             on delete cascade
--             on update cascade,
--     constraint models_exel_autoru_mark_inner_id_fk
--         foreign key("autoru_mark_inner_id")
--             references marks_exel("inner_id")
--             on delete cascade
--             on update cascade,
--     unique(inner_id)
-- );

-- create table generations_exel (
--     "id" serial primary key,
--     "autoru_mark_id" int not null,
--     "autoru_mark_inner_id" character varying(50) not null,
--     "autoru_model_id" int not null,
--     "autoru_model_inner_id" character varying(50) not null,
--     "inner_id" int not null,
--     "name" character varying(50) not null,
--     "photo_main" text,
--     "photo_main_minicard" text,
--     "photo_mobile" text,
--     "year_from" int not null,
--     "year_to" int not null,
--     "updated_at" timestamp not null default now(),
--     "created_at" timestamp not null default now(),
--     constraint generations_exel_autoru_mark_id_fk
--         foreign key("autoru_mark_id")
--             references marks_exel("id")
--             on delete cascade
--             on update cascade,
--     constraint generations_exel_autoru_mark_inner_id_fk
--         foreign key("autoru_mark_inner_id")
--             references marks_exel("inner_id")
--             on delete cascade
--             on update cascade,
--     constraint generations_exel_autoru_model_id_fk
--         foreign key("autoru_model_id")
--             references models_exel("id")
--             on delete cascade
--             on update cascade,
--     unique(inner_id)
-- );


-- create table configurations_exel (
--     "id" serial primary key,
--     "autoru_mark_id" int not null,
--     "autoru_mark_inner_id" character varying(50) not null,
--     "autoru_generation_id" int not null,
--     "autoru_generation_inner_id" int not null,
--     "inner_id" int not null,
--     "name" character varying(50) not null,
--     "autoru_body_type" character varying(50),
--     "body_type" character varying(50),
--     "photo_main" text,
--     "photo_main_minicard" text,
--     "photo_mobile" text,
--     "updated_at" timestamp not null default now(),
--     "created_at" timestamp not null default now(),
--     constraint configurations_exel_autoru_mark_id_fk
--         foreign key("autoru_mark_id")
--             references marks_exel("id")
--             on delete cascade
--             on update cascade,
--     constraint configurations_exel_autoru_mark_inner_id_fk
--         foreign key("autoru_mark_inner_id")
--             references marks_exel("inner_id")
--             on delete cascade
--             on update cascade,
--     constraint configurations_exel_autoru_generation_inner_id_fk
--         foreign key("autoru_generation_inner_id")
--             references generations_exel("inner_id")
--             on delete cascade
--             on update cascade,
--     constraint configurations_exel_autoru_generation_id_fk
--         foreign key("autoru_generation_id")
--             references generations_exel("id")
--             on delete cascade
--             on update cascade,
--     unique(inner_id)
-- );


-- create table complectations_exel (
--     "id" serial primary key,
--     "autoru_mark_id" int not null,
--     "autoru_mark_inner_id" character varying(50) not null,
--     "autoru_configuration_id" int not null,
--     "autoru_configuration_inner_id" int not null,
--     "inner_id" int not null,
--     "name" character varying(50) not null,
--     "full_name" character varying(50) not null,
--     "main_fields" jsonb,
--     "packages" jsonb,
--     "specifications" jsonb,
--     "autoru_body_type" character varying(50),
--     "body_type" character varying(50),
--     "photo_main" text,
--     "photo_main_minicard" text,
--     "photo_mobile" text,
--     "updated_at" timestamp not null default now(),
--     "created_at" timestamp not null default now(),
--     -- constraint complectations_exel_autoru_mark_id_fk
--     --     foreign key("autoru_mark_id")
--     --         references marks_exel("id")
--     --         on delete cascade
--     --         on update cascade,
--     constraint complectations_exel_autoru_mark_inner_id_fk
--         foreign key("autoru_mark_inner_id")
--             references marks_exel("inner_id")
--             on delete cascade
--             on update cascade,
--     constraint complectations_exel_autoru_configuration_inner_id_fk
--         foreign key("autoru_configuration_inner_id")
--             references configurations_exel("inner_id")
--             on delete cascade
--             on update cascade,
--     constraint complectations_exel_autoru_configuration_id_fk
--         foreign key("autoru_configuration_id")
--             references configurations_exel("id")
--             on delete cascade
--             on update cascade,
--     unique(inner_id)
-- );

